baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Donald Isaac Grimmer
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Personal Projects
          url: personal/
          weight: 2 
        - name: Farm Projects
          url: farm/
          weight: 3
        - name: Commentary
          url: commentary/
          weight: 4

params:
    description: "This website hosts Donald Isaac Grimmer's curriculum vitae, personal projects, and contact information."
    author: Donald Isaac Grimmer
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Donald Isaac Grimmer
          subtitle: "I am a student at the University of British Columbia - Okanagan's School of Engineering pursuing a Bachelor of Civil Engineering degree. My interests include transportation engineering, infrastructure management, construction management, and water resources engineering. On this website, you can find my curriculum vitae, personal projects, and contact information."
          imageUrl: "picture.png"
          imageWidth: 320
          imageHeight: 152
          buttons:
            - name: Personal Projects
              url: personal/
            - name: Farm Projects
              url: farm/
            - name: Commentary
              url: commentary/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:isaac@grmr.ca
        - name: Phone
          url: tel:+12502220421
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: LinkedIn
          url: https://www.linkedin.com/in/donaldgrimmer
        - name: GitHub
          url: https://github.com/itsdonaldg
        - name: YouTube
          url: https://www.youtube.com/donaldgrimmer

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Donald Isaac Grimmer"
      icon: "picture.png"
      iconWidth: 80 
      iconHeight: 38

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2